version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.2
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    environment:
     - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka:3.2.2
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - KAFK_BROKER_ID=1
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  mysql:
    image: debezium/example-mysql:0.5
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw 
  connect:
    build: .
    image: debezium/connect:confluent
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
     - CONNECT_REST_PORT=8083
     - CONNECT_GROUP_ID=1
     - CONNECT_CONFIG_STORAGE_TOPIC=my_connect_configs
     - CONNECT_OFFSET_STORAGE_TOPIC=my_connect_offsets
     - CONNECT_STATUS_STORAGE_TOPIC=my_connect_status
     - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_REST_ADVERTISED_HOST_NAME=connect
